// Install a SKILL.md extracted from an Archon note into the local repo.
//
// Each provider gets its own dot-directory; there is no canonical
// `<repo>/skills/` source and no `<repo>/AGENTS.md` generated by this tool.
//
// Providers:
//   claude      — .claude/skills/<name>/SKILL.md      (verbatim source)
//   cursor      — .cursor/rules/<name>.mdc            (Cursor frontmatter: description / globs / alwaysApply)
//   windsurf    — .windsurf/rules/<name>.md           (verbatim source)
//   copilot     — .github/instructions/<name>.instructions.md  (Copilot frontmatter: applyTo / description)
//   antigravity — .agents/skills/<name>/SKILL.md      (verbatim source)
//   opencode    — .opencode/agents/<name>.md          (verbatim source)
//
// Zero runtime deps; stdlib only.

import { mkdirSync, writeFileSync } from "node:fs";
import { join, relative, resolve } from "node:path";

export type Provider =
  | "claude"
  | "cursor"
  | "windsurf"
  | "copilot"
  | "antigravity"
  | "opencode";

export const ALL_PROVIDERS: Provider[] = [
  "claude",
  "cursor",
  "windsurf",
  "copilot",
  "antigravity",
  "opencode",
];

export type InstallWrite = {
  provider: Provider;
  path: string;
  mode: "copy" | "generate";
};

export type InstallSkillReport = {
  skillName: string;
  description: string;
  wrote: InstallWrite[];
};

export type InstallSkillOptions = {
  /** Raw `content` field from an Archon note — may be a wrapped ` ```markdown ` fence or raw SKILL.md. */
  noteContent: string;
  /** Repo root where .claude/, .cursor/, .windsurf/, .github/, .agents/, .opencode/ live. */
  repoPath: string;
  /** Subset of providers. Default: ["claude"] only — pass an explicit list to target other editors. */
  providers?: Provider[];
};

/** Extract `{ name, description, body }` from note content. Handles two cases:
 *  (a) content is raw SKILL.md starting with `---\nname: …`,
 *  (b) content is a wrapped note whose first ` ```markdown ` fence contains the SKILL.md.
 */
export function extractSkillFromNoteContent(noteContent: string): {
  name: string;
  description: string;
  body: string;
} {
  // Case (a): raw SKILL.md
  if (noteContent.startsWith("---\n")) {
    const parsed = parseFrontmatter(noteContent);
    if (parsed.meta.name && parsed.meta.description) {
      return {
        name: parsed.meta.name,
        description: parsed.meta.description,
        body: noteContent,
      };
    }
  }

  // Case (b): find the first fenced markdown block whose inner content starts with a frontmatter block.
  // The opening fence may be ≥3 backticks; the closing fence must be exactly the same count
  // (so a SKILL body wrapped in 4 backticks can safely nest 3-backtick code blocks inside).
  const fenceRe = /(`{3,})markdown\n([\s\S]*?)\n\1(?!`)/g;
  let m: RegExpExecArray | null;
  while ((m = fenceRe.exec(noteContent)) !== null) {
    const inner = m[2];
    if (!inner.startsWith("---\n")) continue;
    const parsed = parseFrontmatter(inner);
    if (parsed.meta.name && parsed.meta.description) {
      return {
        name: parsed.meta.name,
        description: parsed.meta.description,
        body: inner,
      };
    }
  }

  throw new Error(
    "install-skill: note content does not contain a SKILL.md block with both 'name' and 'description' in its frontmatter",
  );
}

function parseFrontmatter(raw: string): {
  meta: Record<string, string>;
  body: string;
} {
  if (!raw.startsWith("---\n")) return { meta: {}, body: raw };
  const end = raw.indexOf("\n---", 4);
  if (end === -1) return { meta: {}, body: raw };
  const fmBlock = raw.slice(4, end);
  const afterCloser = raw.indexOf("\n", end + 4);
  const body = afterCloser === -1 ? "" : raw.slice(afterCloser + 1);
  const meta: Record<string, string> = {};
  for (const line of fmBlock.split("\n")) {
    const match = line.match(/^([A-Za-z_][A-Za-z0-9_-]*):\s*(.*)$/);
    if (match) meta[match[1]] = match[2].trim();
  }
  return { meta, body };
}

/** Strip the leading `---\n…\n---\n` frontmatter off a SKILL.md body.
 *  Used for providers that reject the source frontmatter (Cursor, Copilot). */
function stripFrontmatter(body: string): string {
  if (!body.startsWith("---\n")) return body;
  const end = body.indexOf("\n---", 4);
  if (end === -1) return body;
  const afterCloser = body.indexOf("\n", end + 4);
  return afterCloser === -1 ? "" : body.slice(afterCloser + 1).replace(/^\n+/, "");
}

/** YAML-safe string: always JSON-quote. YAML is a JSON superset for flow scalars. */
function yamlStr(s: string): string {
  return JSON.stringify(s);
}

function ensureDir(dir: string): void {
  mkdirSync(dir, { recursive: true });
}

export function installSkill(opts: InstallSkillOptions): InstallSkillReport {
  const { name, description, body } = extractSkillFromNoteContent(opts.noteContent);
  const repo = resolve(opts.repoPath);
  const providers = opts.providers ?? ["claude"];

  const wrote: InstallWrite[] = [];

  for (const provider of providers) {
    switch (provider) {
      case "claude": {
        const dstDir = join(repo, ".claude", "skills", name);
        ensureDir(dstDir);
        const dst = join(dstDir, "SKILL.md");
        writeFileSync(dst, body);
        wrote.push({ provider, path: dst, mode: "copy" });
        break;
      }
      case "antigravity": {
        const dstDir = join(repo, ".agents", "skills", name);
        ensureDir(dstDir);
        const dst = join(dstDir, "SKILL.md");
        writeFileSync(dst, body);
        wrote.push({ provider, path: dst, mode: "copy" });
        break;
      }
      case "cursor": {
        const dstDir = join(repo, ".cursor", "rules");
        ensureDir(dstDir);
        const dst = join(dstDir, `${name}.mdc`);
        const out = [
          "---",
          `description: ${yamlStr(description)}`,
          `globs: "**/*"`,
          `alwaysApply: false`,
          "---",
          "",
          stripFrontmatter(body),
        ].join("\n");
        writeFileSync(dst, out);
        wrote.push({ provider, path: dst, mode: "generate" });
        break;
      }
      case "windsurf": {
        const dstDir = join(repo, ".windsurf", "rules");
        ensureDir(dstDir);
        const dst = join(dstDir, `${name}.md`);
        writeFileSync(dst, body);
        wrote.push({ provider, path: dst, mode: "copy" });
        break;
      }
      case "copilot": {
        const dstDir = join(repo, ".github", "instructions");
        ensureDir(dstDir);
        const dst = join(dstDir, `${name}.instructions.md`);
        const out = [
          "---",
          `applyTo: "**/*"`,
          `description: ${yamlStr(description)}`,
          "---",
          "",
          stripFrontmatter(body),
        ].join("\n");
        writeFileSync(dst, out);
        wrote.push({ provider, path: dst, mode: "generate" });
        break;
      }
      case "opencode": {
        const dstDir = join(repo, ".opencode", "agents");
        ensureDir(dstDir);
        const dst = join(dstDir, `${name}.md`);
        writeFileSync(dst, body);
        wrote.push({ provider, path: dst, mode: "copy" });
        break;
      }
    }
  }

  return {
    skillName: name,
    description,
    wrote: wrote.map((w) => ({ ...w, path: relative(repo, w.path) })),
  };
}
